CREATE DATABASE CRUD;

USE CRUD;

CREATE TABLE CLIENTE(
    CLIENTEID INT IDENTITY (1, 1)NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL
) CREATE TABLE PEDIDO(
    PEDIDOID INT IDENTITY (1, 1)NOT NULL PRIMARY KEY,
    DESCRIPCION VARCHAR (100),
    FECHAPEDIDO DATETIME NOT NULL,
    CLIENTEID INT NOT NULL,
    CONSTRAINT FK_CLIENTE_PEDIDO_CLIENTEID FOREIGN KEY (CLIENTEID) REFERENCES CLIENTE(CLIENTEID)ON DELETE CASCADE
)